version: 2
updates:
  - package-ecosystem: gomod
    directory: /cmcc
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /gotify-plugin
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /server
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
